server:
  port: 0

spring:
  application:
    name: eureka-upload-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka

feign:
  circuitbreaker:
    enabled: true
